{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintNew where

-- pretty-printer generated by the BNF converter

import AbsNew
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
    PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print Def where
  prt i e = case e of
    DFun fun -> prPrec i 0 (concatD [prt 0 fun])
    DIFun infun -> prPrec i 0 (concatD [prt 0 infun])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print InFun where
  prt i e = case e of
    InlineFunction fun -> prPrec i 0 (concatD [doc (showString "inline"), prt 0 fun])

instance Print Fun where
  prt i e = case e of
    FuctionHead type_ id args funbod -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 funbod])

instance Print FunBod where
  prt i e = case e of
    FunctionBody -> prPrec i 0 (concatD [doc (showString ";")])

instance Print Arg where
  prt i e = case e of
    ArgIdLess type_ -> prPrec i 0 (concatD [prt 0 type_])
    ArgId type_ name -> prPrec i 0 (concatD [prt 0 type_, prt 0 name])
    ArgIdDefault type_ name exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 name, doc (showString "="), prt 0 exp])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Type where
  prt i e = case e of
    TName name -> prPrec i 0 (concatD [prt 0 name])
    TConst name -> prPrec i 0 (concatD [doc (showString "const"), prt 0 name])
    TRef type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&")])

instance Print Value where
  prt i e = case e of
    VInt n -> prPrec i 0 (concatD [prt 0 n])
    VDouble d -> prPrec i 0 (concatD [prt 0 d])
    VChar c -> prPrec i 0 (concatD [prt 0 c])
    ValString valstrings -> prPrec i 0 (concatD [prt 0 valstrings])

instance Print ValString where
  prt i e = case e of
    ValSingleString str -> prPrec i 0 (concatD [prt 0 str])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Name where
  prt i e = case e of
    Name id -> prPrec i 0 (concatD [prt 0 id])

instance Print QConst where
  prt i e = case e of
    QConstBase name -> prPrec i 0 (concatD [prt 0 name])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString "::"), prt 0 xs])
instance Print Exp where
  prt i e = case e of
    ExValue value -> prPrec i 16 (concatD [prt 0 value])
    ExName name -> prPrec i 16 (concatD [prt 0 name])
    ExIndex exp1 exp2 -> prPrec i 15 (concatD [prt 16 exp1, doc (showString "["), prt 16 exp2, doc (showString "]")])
    ExCall exp exps -> prPrec i 15 (concatD [prt 16 exp, doc (showString "("), prt 0 exps, doc (showString ")")])
    ExQConst qconsts -> prPrec i 15 (concatD [prt 0 qconsts])
    ExProjPoint exp1 exp2 -> prPrec i 14 (concatD [prt 15 exp1, doc (showString "."), prt 15 exp2])
    ExProjArrow exp1 exp2 -> prPrec i 14 (concatD [prt 15 exp1, doc (showString "->"), prt 15 exp2])
    ExPostInc exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "++")])
    ExPostDec exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "--")])
    ExDeref exp -> prPrec i 14 (concatD [doc (showString "*"), prt 15 exp])
    ExPreInc exp -> prPrec i 13 (concatD [doc (showString "++"), prt 14 exp])
    ExPreDec exp -> prPrec i 13 (concatD [doc (showString "--"), prt 14 exp])
    ExNot exp -> prPrec i 13 (concatD [doc (showString "!"), prt 14 exp])
    ExMult exp1 exp2 -> prPrec i 12 (concatD [prt 13 exp1, doc (showString "*"), prt 13 exp2])
    ExDiv exp1 exp2 -> prPrec i 12 (concatD [prt 13 exp1, doc (showString "/"), prt 13 exp2])
    ExMod exp1 exp2 -> prPrec i 12 (concatD [prt 13 exp1, doc (showString "%"), prt 13 exp2])
    ExAdd exp1 exp2 -> prPrec i 11 (concatD [prt 12 exp1, doc (showString "+"), prt 12 exp2])
    ExSub exp1 exp2 -> prPrec i 11 (concatD [prt 12 exp1, doc (showString "-"), prt 12 exp2])
    ExLeftShft exp1 exp2 -> prPrec i 10 (concatD [prt 11 exp1, doc (showString "<<"), prt 11 exp2])
    ExRightSft exp1 exp2 -> prPrec i 10 (concatD [prt 11 exp1, doc (showString ">>"), prt 11 exp2])
    ExLess exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString "<"), prt 10 exp2])
    ExGreater exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString ">"), prt 10 exp2])
    ExLessEq exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString "<="), prt 10 exp2])
    ExGreaterEq exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString ">="), prt 10 exp2])
    ExEqual exp1 exp2 -> prPrec i 8 (concatD [prt 9 exp1, doc (showString "=="), prt 9 exp2])
    ExInequal exp1 exp2 -> prPrec i 8 (concatD [prt 9 exp1, doc (showString "!="), prt 9 exp2])
    ExConjunc exp1 exp2 -> prPrec i 4 (concatD [prt 5 exp1, doc (showString "&&"), prt 5 exp2])
    ExDisjunc exp1 exp2 -> prPrec i 3 (concatD [prt 4 exp1, doc (showString "||"), prt 4 exp2])
    ExAssign exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "="), prt 3 exp2])
    ExAddAssign exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "+="), prt 3 exp2])
    ExSubAssign exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "-="), prt 3 exp2])
    ExCond exp1 exp2 exp3 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "?"), prt 3 exp2, doc (showString ":"), prt 3 exp3])
    ExThrow exp -> prPrec i 1 (concatD [doc (showString "throw"), prt 0 exp])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])

