{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintGrammar where

-- pretty-printer generated by the BNF converter

import AbsGrammar
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)



instance Print Id where
  prt _ (Id i) = doc (showString ( i))
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])


instance Print Program where
  prt i e = case e of
    PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print Def where
  prt i e = case e of
    DFun type_ id args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
    DFunIn type_ id args stms -> prPrec i 0 (concatD [doc (showString "inline"), prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
    DTypdf type_ id -> prPrec i 0 (concatD [doc (showString "typedef"), prt 0 type_, prt 0 id, doc (showString ";")])
    DVarDec type_ id ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString ","), prt 0 ids, doc (showString ";")])
    DVarIn type_ id exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp, doc (showString ";")])
    DStruct id structdecs -> prPrec i 0 (concatD [doc (showString "struct"), prt 0 id, doc (showString "{"), prt 0 structdecs, doc (showString "}"), doc (showString ";")])
    Dusing type_ -> prPrec i 0 (concatD [doc (showString "using"), prt 0 type_, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print StructDec where
  prt i e = case e of
    Struct type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Arg where
  prt i e = case e of
    ArgDec1 type_ -> prPrec i 0 (concatD [prt 0 type_])
    ArgDec2 type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
    ArgDec3 type_ id exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp])
    ArgConst type_ id -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, doc (showString "&"), prt 0 id])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Stm where
  prt i e = case e of
    StmExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    StmDec decs -> prPrec i 0 (concatD [prt 0 decs, doc (showString ";")])
    StmReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    StmWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    StmDoWhil stm1 exp stm2 -> prPrec i 0 (concatD [doc (showString "do"), prt 0 stm1, doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm2])
    StmFor type_ id exp1 exp2 exp3 stm -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp1, doc (showString ";"), prt 0 exp2, doc (showString ";"), prt 0 exp3, doc (showString ")"), prt 0 stm])
    StmIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    StmIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString ";"), doc (showString "else"), prt 0 stm2])
    StmBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    StmTypeDef type_ id -> prPrec i 0 (concatD [doc (showString "typedef"), prt 0 type_, prt 0 id, doc (showString ";")])
    StmStruct id structdecs -> prPrec i 0 (concatD [doc (showString "struct"), prt 0 id, doc (showString "{"), prt 0 structdecs, doc (showString "}"), doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Dec where
  prt i e = case e of
    StmDec1 type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString ";")])
    StmDec2 type_ id exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp, doc (showString ";")])
    StmDec3 type_ id ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString ","), prt 0 ids, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Exp where
  prt i e = case e of
    ExInt n -> prPrec i 16 (concatD [prt 0 n])
    ExDouble d -> prPrec i 16 (concatD [prt 0 d])
    ExChar c -> prPrec i 16 (concatD [prt 0 c])
    ExString strs -> prPrec i 16 (concatD [prt 0 strs])
    ExIndex id exp -> prPrec i 15 (concatD [prt 0 id, doc (showString "["), prt 0 exp, doc (showString "]")])
    ExQualConst id1 id2 -> prPrec i 15 (concatD [prt 0 id1, doc (showString "::"), prt 0 id2])
    ExFunCall id exps -> prPrec i 15 (concatD [prt 0 id, doc (showString "("), prt 0 exps, doc (showString ")")])
    ExStrProj1 exp1 exp2 -> prPrec i 14 (concatD [prt 0 exp1, doc (showString "."), prt 0 exp2])
    ExStrProj2 exp1 exp2 -> prPrec i 14 (concatD [prt 0 exp1, doc (showString "->"), prt 0 exp2])
    ExInc1 exp -> prPrec i 14 (concatD [prt 0 exp, doc (showString "++")])
    ExDec1 exp -> prPrec i 14 (concatD [prt 0 exp, doc (showString "--")])
    ExDeref exp -> prPrec i 14 (concatD [doc (showString "*"), prt 0 exp])
    ExInc2 exp -> prPrec i 13 (concatD [doc (showString "++"), prt 0 exp])
    ExDec2 exp -> prPrec i 13 (concatD [doc (showString "--"), prt 0 exp])
    ExNeg exp -> prPrec i 13 (concatD [doc (showString "!"), prt 0 exp])
    ExMult exp1 exp2 -> prPrec i 12 (concatD [prt 0 exp1, doc (showString "*"), prt 0 exp2])
    ExDiv exp1 exp2 -> prPrec i 12 (concatD [prt 0 exp1, doc (showString "/"), prt 0 exp2])
    ExRem exp1 exp2 -> prPrec i 12 (concatD [prt 0 exp1, doc (showString "%"), prt 0 exp2])
    ExpAdd exp1 exp2 -> prPrec i 11 (concatD [prt 0 exp1, doc (showString "+"), prt 0 exp2])
    ExSub exp1 exp2 -> prPrec i 11 (concatD [prt 0 exp1, doc (showString "-"), prt 0 exp2])
    ExLeftSh exp1 exp2 -> prPrec i 10 (concatD [prt 0 exp1, doc (showString "<<"), prt 0 exp2])
    ExRightSh exp1 exp2 -> prPrec i 10 (concatD [prt 0 exp1, doc (showString ">>"), prt 0 exp2])
    ExComp1 exp1 exp2 -> prPrec i 9 (concatD [prt 0 exp1, doc (showString "<"), prt 0 exp2])
    ExComp2 exp1 exp2 -> prPrec i 9 (concatD [prt 0 exp1, doc (showString ">"), prt 0 exp2])
    ExComp3 exp1 exp2 -> prPrec i 9 (concatD [prt 0 exp1, doc (showString ">="), prt 0 exp2])
    ExComp4 exp1 exp2 -> prPrec i 9 (concatD [prt 0 exp1, doc (showString "<="), prt 0 exp2])
    ExEqual exp1 exp2 -> prPrec i 8 (concatD [prt 0 exp1, doc (showString "=="), prt 0 exp2])
    ExInequal exp1 exp2 -> prPrec i 8 (concatD [prt 0 exp1, doc (showString "!="), prt 0 exp2])
    ExConj exp1 exp2 -> prPrec i 4 (concatD [prt 0 exp1, doc (showString "&&"), prt 0 exp2])
    ExDisj exp1 exp2 -> prPrec i 3 (concatD [prt 0 exp1, doc (showString "||"), prt 0 exp2])
    ExAssig1 exp1 exp2 -> prPrec i 2 (concatD [prt 0 exp1, doc (showString "="), prt 0 exp2])
    ExAssig2 exp1 exp2 -> prPrec i 2 (concatD [prt 0 exp1, doc (showString "+="), prt 0 exp2])
    ExAssig3 exp1 exp2 -> prPrec i 2 (concatD [prt 0 exp1, doc (showString "-="), prt 0 exp2])
    ExCond1 exp1 exp2 -> prPrec i 2 (concatD [prt 0 exp1, doc (showString "?"), prt 0 exp2])
    ExCond2 exp1 exp2 -> prPrec i 2 (concatD [prt 0 exp1, doc (showString ":"), prt 0 exp2])
    ExExep exp -> prPrec i 1 (concatD [doc (showString "throw"), prt 0 exp])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Type where
  prt i e = case e of
    Typbool -> prPrec i 0 (concatD [doc (showString "bool")])
    Typdouble -> prPrec i 0 (concatD [doc (showString "double")])
    Typint -> prPrec i 0 (concatD [doc (showString "int")])
    Typvoid -> prPrec i 0 (concatD [doc (showString "void")])


